# Generated by Django 4.1.7 on 2023-03-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_rename_nome_estado_name_delete_cidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='Locais',
        ),
    ]
