# Generated by Django 4.1.7 on 2023-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0006_rename_estados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
