# Generated by Django 4.1.7 on 2023-03-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_alter_estado_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
