# Generated by Django 4.1.7 on 2023-03-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
